# Generated by Django 3.2.7 on 2021-09-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
