# Generated by Django 3.2.7 on 2021-10-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_backend', '0002_alter_articles_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
